USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;
CREATE TABLE IF NOT EXISTS HELLO_WORLD
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);
CREATE TABLE IF NOT EXISTS HELLO_WORLD_1
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);
