USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;
ALTER TABLE HELLO_WORLD ADD COLUMN AGE NUMBER;
INSERT INTO HELLO_WORLD (FIRST_NAME, LAST_NAME, AGE) VALUES ('ABC','XYZ',25);
CREATE TABLE IF NOT EXISTS HELLO_WORLD_1
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);
